### PR TITLE
Basic wandb support

### PR DESCRIPTION
**Pull request by vanpelt**
# Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos, doc improvements)
- [ ] Did you read the [contributor guideline](https://github.com/williamFalcon/pytorch-lightning/blob/master/.github/CONTRIBUTING.md)?
- [ ] Did you make sure to update the docs?   
- [ ] Did you write any new necessary tests?  

## What does this PR do?
Fixes # (issue).

## PR review    
Anyone in the community is free to review the PR once the tests have passed.     
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

## Did you have fun?
Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by borisdayma** [comment]
I still have a test that fails related to pickling.

```
pkl_bytes = pickle.dumps(trainer)
E       AttributeError: Can't pickle local object '_createenviron.<locals>.encode'
```

Once it's fixed I'll test more on some examples.

**Comment by vanpelt** [comment]
Nice, looking good so far.  Not sure what the pickle error is...

**Comment by borisdayma** [comment]
I think it's because the object returned by wandb.init cannot be pickled. Sometimes it's when there is use of multiprocessing in the module.
I'm going to try a few different things.

**Comment by vanpelt** [comment]
Ahh, the object is in wandb_run.py we should be able to override the to and from pickle methods.

**Comment by borisdayma** [comment]
Had to do several changes to merge with master. Now it should be good to go!
Did the test on MNIST example it seemed to all work fine and logged on W&B.

**Pull request closed without merging**
